-- attribution-fixes-2026-07-18.sql — jesse-pujji attribution audit (ledger: attribution-audit-2026-07-18.json)
-- 23 KEEP-normalize (batch by exact old source_ref — each covers every atom sharing that ref, 352 atoms total) + 31 REATTR, all per-id. 2 STRIP proposals demoted to residue on review; 31+2 RESIDUE atoms intentionally untouched.
-- Dates from the verified public-record date_corrections map only; sources without a verified date get source_ref only.
-- Does not touch claim_type / verification / embedding.
BEGIN;
UPDATE jesse_pujji_atoms SET source_ref='How Founders Should Be Integrating AI — Alex Lieberman & Jesse Pujji', source_date='2023-05-16' WHERE source_ref='youtube:How-Founders-Should-Be-Integrating-AI';
UPDATE jesse_pujji_atoms SET source_ref='Jesse Pujji on Bootstrapping a +$1B Business + Selling To The Ultra Rich', source_date='2024-08-26' WHERE source_ref='youtube:Jesse_Pujji_bootstrapping_1B';
UPDATE jesse_pujji_atoms SET source_ref='Jesse Pujji Reveals How He''s Building His HoldCo (Gateway X) — Confessions of a B2B Entrepreneur', source_date='2024-08-07' WHERE source_ref='youtube:Jesse_Pujji_GatewayX_Confessions_B2B';
UPDATE jesse_pujji_atoms SET source_ref='Mobile Commerce and Storytelling — EP186 Jesse Pujji', source_date='2023-05-16' WHERE source_ref='youtube:EP186-jesse-pujji';
UPDATE jesse_pujji_atoms SET source_ref='Interview w/ Jesse Pujji, Co-founder at Ampush', source_date='2021-11-12' WHERE source_ref='interview_jesse_pujji_ampush';
UPDATE jesse_pujji_atoms SET source_ref='Bootstrapping My First Company to $10M' WHERE source_ref='Bootstrapping My First Company to $10M — essay';
UPDATE jesse_pujji_atoms SET source_ref='Bootstrapping My First Company to $10M' WHERE source_ref='Bootstrapping My First Company to $10M - essay';
UPDATE jesse_pujji_atoms SET source_ref='Bootstrapping My First Company to $10M' WHERE source_ref='Bootstrapping My First Company to $10M essay';
UPDATE jesse_pujji_atoms SET source_ref='How I Built These Companies - Bootstrapped Giants', source_date='2025-09-28' WHERE source_ref='How I Built These Companies - Bootstrapped Giants — essay';
UPDATE jesse_pujji_atoms SET source_ref='How I Built These Companies - Bootstrapped Giants', source_date='2025-09-28' WHERE source_ref='How I Built These Companies - Bootstrapped Giants essay';
UPDATE jesse_pujji_atoms SET source_ref='How I Built These Companies - Bootstrapped Giants', source_date='2025-09-28' WHERE source_ref='How I Built These Companies - Bootstrapped Giants - essay';
UPDATE jesse_pujji_atoms SET source_ref='A Primer on Performance Marketing - Founder''s Field Guide', source_date='2021-04-01' WHERE source_ref='A Primer on Performance Marketing - Founder''s Field Guide — podcast';
UPDATE jesse_pujji_atoms SET source_ref='A Primer on Performance Marketing - Founder''s Field Guide', source_date='2021-04-01' WHERE source_ref='A Primer on Performance Marketing - Founder''s Field Guide podcast';
UPDATE jesse_pujji_atoms SET source_ref='A Primer on Performance Marketing - Happy Scribe', source_date='2021-04-01' WHERE source_ref='A Primer on Performance Marketing - Happy Scribe / Spotify podcast';
UPDATE jesse_pujji_atoms SET source_ref='How DTC Brands Boom and Bust - Mission.org', source_date='2021-12-16' WHERE source_ref='How DTC Brands Boom and Bust - Mission.org interview';
UPDATE jesse_pujji_atoms SET source_ref='How DTC Brands Boom and Bust - Mission.org', source_date='2021-12-16' WHERE source_ref='How DTC Brands Boom and Bust - Mission.org — interview';
UPDATE jesse_pujji_atoms SET source_ref='Entrepreneurship to Propel Personal Growth - Founders Journal Podcast', source_date='2024-05-14' WHERE source_ref='Entrepreneurship to Propel Personal Growth - Founders Journal Podcast — podcast';
UPDATE jesse_pujji_atoms SET source_ref='How Jesse Pujji Rewired His Mind - Don''t Be a Jerk Podcast', source_date='2025-12-02' WHERE source_ref='How Jesse Pujji Rewired His Mind - Don''t Be a Jerk Podcast — podcast';
UPDATE jesse_pujji_atoms SET source_ref='My Mentor is the Founder of a $10B Company' WHERE source_ref='My Mentor is the Founder of a $10B Company — essay';
UPDATE jesse_pujji_atoms SET source_ref='My Mentor is the Founder of a $10B Company' WHERE source_ref='My Mentor is the Founder of a $10B Company - essay';
UPDATE jesse_pujji_atoms SET source_ref='My Mentor is the Founder of a $10B Company' WHERE source_ref='My Mentor is the Founder of a $10B Company essay';
UPDATE jesse_pujji_atoms SET source_ref='Jesse Pujji Twitter Highlights' WHERE source_ref='Jesse Pujji Twitter Highlights — other';
UPDATE jesse_pujji_atoms SET source_ref='Jesse Pujji LinkedIn Profile' WHERE source_ref='Jesse Pujji LinkedIn Profile — profile';
UPDATE jesse_pujji_atoms SET source_ref='Massive Revenue Growth & Operational Excellence — Jesse Pujji''s Journey from Ampush to Gateway X', source_date='2025-06-29' WHERE id='cfcdb5da-22fa-483f-8617-726408fe547e';
UPDATE jesse_pujji_atoms SET source_ref='An interview with Jesse Pujji, founder & CEO of Gateway X', source_date='2023-10-09' WHERE id='1b5a1d67-61c7-4395-89db-c604437d8205';
UPDATE jesse_pujji_atoms SET source_ref='Massive Revenue Growth & Operational Excellence — Jesse Pujji''s Journey from Ampush to Gateway X', source_date='2025-06-29' WHERE id='4c149726-1ab1-498d-8c1a-4985ec948d98';
UPDATE jesse_pujji_atoms SET source_ref='Massive Revenue Growth & Operational Excellence — Jesse Pujji''s Journey from Ampush to Gateway X', source_date='2025-06-29' WHERE id='7203aaad-c38e-4295-918d-e23b15253d94';
UPDATE jesse_pujji_atoms SET source_ref='Massive Revenue Growth & Operational Excellence — Jesse Pujji''s Journey from Ampush to Gateway X', source_date='2025-06-29' WHERE id='d46881e7-1c2c-4b5c-ba41-2f60b5dce014';
UPDATE jesse_pujji_atoms SET source_ref='Massive Revenue Growth & Operational Excellence — Jesse Pujji''s Journey from Ampush to Gateway X', source_date='2025-06-29' WHERE id='2cd1d903-74dc-452d-a6fa-0af509b286bc';
UPDATE jesse_pujji_atoms SET source_ref='Massive Revenue Growth & Operational Excellence — Jesse Pujji''s Journey from Ampush to Gateway X', source_date='2025-06-29' WHERE id='f6f282b1-e1bb-4a41-b7bb-bd2f9e04c96e';
UPDATE jesse_pujji_atoms SET source_ref='Massive Revenue Growth & Operational Excellence — Jesse Pujji''s Journey from Ampush to Gateway X', source_date='2025-06-29' WHERE id='d328e8b2-eb48-4140-96ed-15456de62f06';
UPDATE jesse_pujji_atoms SET source_ref='Massive Revenue Growth & Operational Excellence — Jesse Pujji''s Journey from Ampush to Gateway X', source_date='2025-06-29' WHERE id='7746393b-fecf-493c-ba51-49bf8f196276';
UPDATE jesse_pujji_atoms SET source_ref='Massive Revenue Growth & Operational Excellence — Jesse Pujji''s Journey from Ampush to Gateway X', source_date='2025-06-29' WHERE id='fd47c4bd-a398-48a4-9528-ac676423a5d9';
UPDATE jesse_pujji_atoms SET source_ref='Massive Revenue Growth & Operational Excellence — Jesse Pujji''s Journey from Ampush to Gateway X', source_date='2025-06-29' WHERE id='ea3b904b-bc16-4042-ab0a-495fadee8b90';
UPDATE jesse_pujji_atoms SET source_ref='Massive Revenue Growth & Operational Excellence — Jesse Pujji''s Journey from Ampush to Gateway X', source_date='2025-06-29' WHERE id='c85616f5-18c6-4318-a1b0-3fad2c7ab95e';
UPDATE jesse_pujji_atoms SET source_ref='Jesse Pujji & Andy Wells (DoorDash) on Marketing, Growth, and Global Talent', source_date='2024-05-21' WHERE id='3239aa4c-8005-48ce-a702-4d005e0fc298';
UPDATE jesse_pujji_atoms SET source_ref='Massive Revenue Growth & Operational Excellence — Jesse Pujji''s Journey from Ampush to Gateway X', source_date='2025-06-29' WHERE id='a8dda089-1b76-407d-be87-905675e89bfb';
UPDATE jesse_pujji_atoms SET source_ref='Massive Revenue Growth & Operational Excellence — Jesse Pujji''s Journey from Ampush to Gateway X', source_date='2025-06-29' WHERE id='5a5ae2cb-0ab5-4e6b-ac15-bc8a26324c70';
UPDATE jesse_pujji_atoms SET source_ref='Massive Revenue Growth & Operational Excellence — Jesse Pujji''s Journey from Ampush to Gateway X', source_date='2025-06-29' WHERE id='d0fbd08d-8142-412f-a93b-c42c0ebd8057';
UPDATE jesse_pujji_atoms SET source_ref='Massive Revenue Growth & Operational Excellence — Jesse Pujji''s Journey from Ampush to Gateway X', source_date='2025-06-29' WHERE id='0245fa76-90cd-4283-84ff-925d07816bf6';
UPDATE jesse_pujji_atoms SET source_ref='Massive Revenue Growth & Operational Excellence — Jesse Pujji''s Journey from Ampush to Gateway X', source_date='2025-06-29' WHERE id='88a0a037-f42b-4c1f-8075-0be20611e870';
UPDATE jesse_pujji_atoms SET source_ref='Massive Revenue Growth & Operational Excellence — Jesse Pujji''s Journey from Ampush to Gateway X', source_date='2025-06-29' WHERE id='07913831-08bb-4a85-bced-44bfdeeefccf';
UPDATE jesse_pujji_atoms SET source_ref='Massive Revenue Growth & Operational Excellence — Jesse Pujji''s Journey from Ampush to Gateway X', source_date='2025-06-29' WHERE id='168b531b-2940-4a8e-9b21-b2a8debcc1d6';
UPDATE jesse_pujji_atoms SET source_ref='Massive Revenue Growth & Operational Excellence — Jesse Pujji''s Journey from Ampush to Gateway X', source_date='2025-06-29' WHERE id='60c2ee23-f741-4009-a0a3-ad5ab5520759';
UPDATE jesse_pujji_atoms SET source_ref='Massive Revenue Growth & Operational Excellence — Jesse Pujji''s Journey from Ampush to Gateway X', source_date='2025-06-29' WHERE id='cf1f5688-1cbe-4998-b476-bcf4fc083f7b';
UPDATE jesse_pujji_atoms SET source_ref='Massive Revenue Growth & Operational Excellence — Jesse Pujji''s Journey from Ampush to Gateway X', source_date='2025-06-29' WHERE id='202e403b-8241-4e37-b5cd-97c848ff28d6';
UPDATE jesse_pujji_atoms SET source_ref='Massive Revenue Growth & Operational Excellence — Jesse Pujji''s Journey from Ampush to Gateway X', source_date='2025-06-29' WHERE id='74d29588-3dfd-4493-be28-cad33042afdf';
UPDATE jesse_pujji_atoms SET source_ref='Massive Revenue Growth & Operational Excellence — Jesse Pujji''s Journey from Ampush to Gateway X', source_date='2025-06-29' WHERE id='4b071503-2bf4-4caf-a195-cea336167dfd';
UPDATE jesse_pujji_atoms SET source_ref='Massive Revenue Growth & Operational Excellence — Jesse Pujji''s Journey from Ampush to Gateway X', source_date='2025-06-29' WHERE id='72e99fed-0add-423a-bfa7-3eed01ddc245';
UPDATE jesse_pujji_atoms SET source_ref='Massive Revenue Growth & Operational Excellence — Jesse Pujji''s Journey from Ampush to Gateway X', source_date='2025-06-29' WHERE id='4d91e90e-7d22-4856-a6bc-42d6ee3676ca';
UPDATE jesse_pujji_atoms SET source_ref='Massive Revenue Growth & Operational Excellence — Jesse Pujji''s Journey from Ampush to Gateway X', source_date='2025-06-29' WHERE id='db29cc43-cc71-4ed4-bab9-e050dab26e44';
UPDATE jesse_pujji_atoms SET source_ref='Massive Revenue Growth & Operational Excellence — Jesse Pujji''s Journey from Ampush to Gateway X', source_date='2025-06-29' WHERE id='5e64a4ad-4697-4ce6-9b56-8099a6c037a5';
UPDATE jesse_pujji_atoms SET source_ref='Massive Revenue Growth & Operational Excellence — Jesse Pujji''s Journey from Ampush to Gateway X', source_date='2025-06-29' WHERE id='46d6fc86-f191-490b-b545-e56f643af2aa';
UPDATE jesse_pujji_atoms SET source_ref='Jesse Pujji & Andy Wells (DoorDash) on Marketing, Growth, and Global Talent', source_date='2024-05-21' WHERE id='f8b4113d-e98d-4da5-8cfb-bc5c92748a35';
COMMIT;
