#!/usr/bin/env python3
"""
sync-claude-md-brains.py — Regenerate the Installed Brains section in
~/rob-ai/CLAUDE.md from brains/index.json.

The brain registry (brainsfor/brains/index.json) is the source of truth. This
script rewrites the table + totals inside the autosync markers in CLAUDE.md so
the doc can never drift from reality.

Usage:
    python3 scripts/sync-claude-md-brains.py              # update CLAUDE.md
    python3 scripts/sync-claude-md-brains.py --check      # exit 1 if drift exists
    python3 scripts/sync-claude-md-brains.py --dry-run    # print, don't write

Markers (must exist in CLAUDE.md):
    <!-- BRAINS_AUTOSYNC_START -->
    <!-- BRAINS_AUTOSYNC_END -->

Called automatically at the end of auto-build-brain.py.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
BRAINSFOR_ROOT = SCRIPT_DIR.parent
ROB_AI_ROOT = BRAINSFOR_ROOT.parent
INDEX_PATH = BRAINSFOR_ROOT / "brains" / "index.json"
CLAUDE_MD_PATH = ROB_AI_ROOT / "CLAUDE.md"

START_MARKER = "<!-- BRAINS_AUTOSYNC_START -->"
END_MARKER = "<!-- BRAINS_AUTOSYNC_END -->"


def short_source(source: str, max_len: int = 110) -> str:
    """Trim long source descriptions for table display."""
    source = source.replace("\n", " ").strip()
    if len(source) <= max_len:
        return source
    cut = source[: max_len - 1]
    # break on word boundary
    if " " in cut:
        cut = cut.rsplit(" ", 1)[0]
    return cut + "…"


def build_section(brains: list[dict]) -> str:
    live = [b for b in brains if b.get("status") == "live"]
    hidden = [b for b in brains if b.get("status") == "hidden"]

    # Sort each group by atom_count descending
    live.sort(key=lambda b: b.get("atom_count", 0), reverse=True)
    hidden.sort(key=lambda b: b.get("atom_count", 0), reverse=True)

    total_atoms = sum(b.get("atom_count", 0) for b in brains)
    total_connections = sum(b.get("connection_count", 0) for b in brains)

    rows = []
    header = "| Slug | Thinker | Atoms | Connections | Status | Source |"
    sep = "|---|---|---|---|---|---|"
    rows.append(header)
    rows.append(sep)
    for b in live + hidden:
        rows.append(
            f"| `{b['slug']}` | {b['name']} | {b['atom_count']} | "
            f"{b['connection_count']} | {b.get('status', 'unknown')} | "
            f"{short_source(b.get('source', ''))} |"
        )

    table = "\n".join(rows)

    intro = (
        f"Rob has {len(brains)} brain packs installed ({len(live)} live, "
        f"{len(hidden)} hidden). Source of truth: `brains/index.json`. "
        f"This table is auto-generated by `scripts/sync-claude-md-brains.py`."
    )

    totals = (
        f"**Totals:** {total_atoms:,} atoms / {total_connections:,} connections "
        f"across {len(brains)} brains. Full registry: "
        f"`~/rob-ai/brainsfor/brains/index.json`."
    )

    return f"{intro}\n\n{table}\n\n{totals}\n"


def replace_section(md: str, new_body: str) -> str:
    if START_MARKER not in md or END_MARKER not in md:
        raise SystemExit(
            "CLAUDE.md is missing the autosync markers. Add:\n"
            f"  {START_MARKER}\n"
            f"  {END_MARKER}\n"
            "around the Installed Brains section."
        )
    pre, rest = md.split(START_MARKER, 1)
    _, post = rest.split(END_MARKER, 1)
    return f"{pre}{START_MARKER}\n{new_body}\n{END_MARKER}{post}"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Exit 1 if drift exists")
    parser.add_argument("--dry-run", action="store_true", help="Print result; do not write")
    args = parser.parse_args()

    if not INDEX_PATH.exists():
        print(f"FATAL: registry not found at {INDEX_PATH}", file=sys.stderr)
        return 2
    if not CLAUDE_MD_PATH.exists():
        print(f"FATAL: CLAUDE.md not found at {CLAUDE_MD_PATH}", file=sys.stderr)
        return 2

    with INDEX_PATH.open() as f:
        registry = json.load(f)
    brains = registry.get("brains", [])
    if not brains:
        print("FATAL: registry has no brains", file=sys.stderr)
        return 2

    new_body = build_section(brains)
    current = CLAUDE_MD_PATH.read_text()
    updated = replace_section(current, new_body)

    if args.check:
        if current != updated:
            print("DRIFT: CLAUDE.md does not match brains/index.json", file=sys.stderr)
            return 1
        print("OK: CLAUDE.md is in sync with brains/index.json")
        return 0

    if args.dry_run:
        print(new_body)
        return 0

    if current == updated:
        print("No changes — CLAUDE.md already in sync.")
        return 0

    CLAUDE_MD_PATH.write_text(updated)
    print(f"Updated {CLAUDE_MD_PATH} — {len(brains)} brains synced.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
